### ISSUE TITLE
Update to match schema call

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-python#23]
The VR-schema utility test was updated to the new "vr" convention instead of "vmc". We need to adjust this to match.

https://github.com/ga4gh/vr-python/blob/aa4c4cea83f8b08229110815e9b8cf41eb812687/tests/validation/test_utils_tests.py#L12

**Comment by ahwagner** [comment]
get_vmc_sequence_identifier is actually defined [here](https://github.com/ga4gh/vr-python/blob/aa4c4cea83f8b08229110815e9b8cf41eb812687/src/ga4gh/vr/extras/seqrepo.py#L34-L49), and referenced at the above (sorry, should have checked closer). It's referenced [in several places](https://github.com/ga4gh/vr-python/search?q=get_vmc_sequence_identifier&unscoped_q=get_vmc_sequence_identifier), actually, so we would need to replace all such instances.

**Comment by reece** [comment]
Not sure when this was resolved, but this file no longer exists and there are no references to get_vmc_sequence_identifier in vr-schema or vr-python any longer.
