### ISSUE TITLE
seqrepo docker container does not create volumes

### ISSUE THREAD

**Issue by melissacline** [ga4gh/vr-python#38]
Under https://github.com/ga4gh/vr-python#installing-dependencies-for-ga4ghvrextras, there is a docker-compose command to fire up the seqrepo rest API.  When you run this command on a fresh installation, it fails twice, instructing you to do "docker volume create" commands, for seqrepo-rest-service and uta respectively.   This isn't a major setback, since the error message gives you exactly the command to execute, and if you enter that command verbatim then everything works fine.  Even though seqrepo isn't part of VR per se, these commands might as well be added to the docker container or the installation instructions.

**Comment by reece** [comment]
Fixed. Thanks for the report, @melissacline.
